[package]
name = "remotefs-memory"
version = "0.1.6"
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
categories = ["simulation"]
documentation = "https://docs.rs/remotefs-memory"
edition = "2021"
include = ["src/**/*", "./LICENSE", "./README.md", "./CHANGELOG.md"]
keywords = ["remotefs", "memory"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs-memory"
description = "remotefs implementation for volatile memory. Good for testing and simulation."

[dependencies]
log = "^0.4"
orange-trees = "0.1"
remotefs = "0.3"

[dev-dependencies]
pretty_assertions = "^1"

[lib]
name = "remotefs_memory"
path = "src/lib.rs"
